### ISSUE TITLE
No audio on PC-BSD 10.0.1 with pulseaudio server

### ISSUE THREAD

**Issue by sysfu** [tomighty/tomighty#102]
I am able to build and launch Tomighty 0.8.0 on PC-BSD 10.0.1 however this is no sound. Here's the relevant output from the console

```
09:45:08.843 [DefaultTimer] ERROR org.tomighty.sound.SoundPlayer - Error while playing sound: org.tomighty.sound.timer.Ding@41822dc7
java.lang.IllegalArgumentException: No line matching interface Clip supporting format PCM_SIGNED unknown sample rate, 16 bit, stereo, 4 bytes/frame, big-endian is supported.
        at javax.sound.sampled.AudioSystem.getLine(AudioSystem.java:476) ~[na:1.6.0_32]
        at javax.sound.sampled.AudioSystem.getClip(AudioSystem.java:520) ~[na:1.6.0_32]
        at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:65) [tomighty-swing-0.8.0-jar-with-dependencies.jar:na]
        at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:51) [tomighty-swing-0.8.0-jar-with-dependencies.jar:na]
        at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:36) [tomighty-swing-0.8.0-jar-with-dependencies.jar:na]
```

**Comment by ccidral** [comment]
Hi @sysfu, thanks again for reporting this other one issue. As I said in another comment, I'm having a hard time finding spare time to work on Tomighty, so I'm afraid I won't be able to look at this issue at any time soon. If someone else could take the time to dig this problem, I would be grateful.
