### ISSUE TITLE
Sounds often fail to play under Linux

### ISSUE THREAD

**Issue by ccidral** [tomighty/tomighty#17]
I noticed that this problem happens when there is another sound intensive application running in parallel.

```
    07/11/2010 17:01:40 org.tomighty.log.Log error
    GRAVE: Error while playing sound: org.tomighty.sound.timer.Ding@148e798
    javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 22050.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
        at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:494)
        at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1280)
        at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:107)
        at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1061)
        at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1151)
        at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:72)
        at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:56)
        at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:41)
        at org.tomighty.ui.state.TimerSupport.countdownFinished(TimerSupport.java:86)
        at org.tomighty.time.CountdownTimer$Updater.run(CountdownTimer.java:51)
        at java.util.TimerThread.mainLoop(Timer.java:512)
        at java.util.TimerThread.run(Timer.java:462)
```

**Comment by ccidral** [comment]
New report by _denholm dot james at gmail dot com_:

Using the 0.6 jar, this is still an issue for myself, at least. The following is output to the terminal:

```
    jdenholm@jamesdenholmlinux:~/Desktop$ java -jar tomighty-0.6.jar
    16/04/2011 2:31:59 PM org.tomighty.log.Log info
    INFO: Loading messages for locale en_AU
    16/04/2011 2:31:59 PM org.tomighty.log.Log info
    INFO: Messages file not found: /messages_en_AU.properties
    16/04/2011 2:32:03 PM org.tomighty.log.Log error               #Pomodoro started here
    SEVERE: Error while playing sound: org.tomighty.sound.timer.Wind@1b7ae22
    java.lang.IllegalArgumentException: Invalid format
        at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.createStream(PulseAudioDataLine.java:143)
        at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:100)
        at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:289)
        at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:402)
        at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:453)
        at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:72)
        at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:56)
        at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:41)
        at org.tomighty.ui.state.TimerSupport.afterRendering(TimerSupport.java:70)
        at org.tomighty.Tomighty.render(Tomighty.java:84)
        at org.tomighty.Tomighty.access$200(Tomighty.java:42)
        at org.tomighty.Tomighty$SwitchState$1.run(Tomighty.java:94)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:226)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:647)
        at java.awt.EventQueue.access$000(EventQueue.java:96)
        at java.awt.EventQueue$1.run(EventQueue.java:608)
        at java.awt.EventQueue$1.run(EventQueue.java:606)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:105)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:617)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)
```

Taken from the original issue at http://code.google.com/p/tomighty/issues/detail?id=31

**Comment by ydm101** [comment]
Audio file format issue most likely due to multiple java homes or libraries used. 

For troubleshooting, ask for the output of the following commands:
1. more /etc/jvm
2. java -version
3. find / -name _java_  
4. find / -name _jdk_
5. Which linux OS distro - Ubuntu XXX ?? Natty / Marvin / Lucid , etc. & if [64 vs 32 bit OS] & does the jvm also match the OS?

**Comment by blanchma** [comment]
OpenJDK Runtime Environment (IcedTea6 1.9.8) (6b20-1.9.8-0ubuntu1~10.04.1)
OpenJDK 64-Bit Server VM (build 19.0-b09, mixed mode)

**Comment by danielestevez** [comment]
Ok, so i made some research on this issue; basically your code is mostly ok but the problem lies in the JVM implementations on Linux.

Official Sun Hotspot VM is not able to access PulseAudio Linux sound system so it just can use ALSA directly causing trouble when you have some other application playing sound (i.e. Spotify). So here we have a trick u may use to force any program running under Linux to use PulseAudio by calling java with 'padsp' command as explained in https://bugs.launchpad.net/ubuntu/+source/sun-java6/+bug/457144 This way you can force the Hotspot VM to use PulseAudio and you can have as many applications playing sounds as you want, Pulse will handle the conflicts.

Now, using OpenJDK i got an InvalidFormatException playing sounds, so no sound at all works with this VM. I tried and fixed this, making the sounds work at first but the application hangs somehow and the solution wasn't compatible with using the Sun implementation. I might try again but this is really hell, first solution, although a bit dirty, works for me.

Cheers!

**Comment by ccidral** [comment]
Good news is that the code is ok.  I was afraid of being forced to make some black magic in order to play sounds correctly on Linux.

I'm not sure about the following but I believe it's possible to select Pulse as the mixer through which Tomighty can play sounds.  It's just a guess, I will try it later on Ubuntu when I arrive home:

_groovy code below_

``` groovy
import javax.sound.sampled.*

AudioSystem.getMixerInfo().each({
    println it.getName()
})
```

If the name "pulse" appear on the output, then we probably will solve the problem by selecting the desired mixer info (pulse) and then doing this:

``` groovy
Clip clip = AudioSystem.getClip(mixerInfo)
```

Only when running on Linux, of course.

**Comment by ccidral** [comment]
Oops, I guess my theory might not work at all.  My brother ran the code above under Ubuntu 10.04 and this is the output:

```
Intel [plughw:0,0]
Intel [plughw:0,1]
Java Sound Audio Engine
Port Intel [hw:0]
```

His system:

```
$ uname -a
Linux euax 2.6.32-29-generic #58-Ubuntu SMP Fri Feb 11 20:52:10 UTC 2011 x86_64 GNU/Linux

$ java -version
OpenJDK Runtime Environment (IcedTea6 1.9.2) (6b20-1.9.2-0ubuntu1~10.04.1)
OpenJDK 64-Bit Server VM (build 19.0-b09, mixed mode)
```

Anyway, I will try some other things based on that.

I forgot the InvalidFormatException you mentioned.  It seems there are 2 different issues here. The first one is the sound system being taken over by the JVM (and failing to do so when another process is using sound resources), and that might happen with both Sun's JVM and OpenJDK, not sure yet. The second one is a file format issue that apparently happens only with OpenJDK. I think it's worth splitting them into two different issues.

**Comment by ccidral** [comment]
On my machine with Ubuntu 11.04:

```
PulseAudio Mixer
default [default]
SIS966 [plughw:0,0]
SIS966 [plughw:0,1]
SIS966 [plughw:0,6]
Port SIS966 [hw:0]
```

```
$ uname -a
Linux moon 2.6.38-8-generic-pae #42-Ubuntu SMP Mon Apr 11 05:17:09 UTC 2011 i686 i686 i386 GNU/Linux
```

The PulseAudio mixer showed up. However, since it is not present in my brother's system, it may not be available in all systems, so trying to pick it up from the list of mixers does not seem to be a universal solution.

**Comment by danielestevez** [comment]
Agreed: AFAIK there is no way to access to Pulse from Sun JDK and i don't think it's possible from Java to address this issue, it's a bug in JVM.
As you say, OpenJDK is a different issue so a specific solution could be found based on the availability of Pulse in a Linux system.

Btw, my machine is running Natty 11.04 too.

Who said Java was WORA? ;)

**Comment by aalsaif** [comment]
I'm having the same issue and it's always happening. 
1. more /etc/jvm
   /etc/jvm: No such file or directory
   but with /etc/java i got
   java/              java-6-openjdk/    java-7-openjdk/    javascript-common/
2. java -version
   java version "1.7.0_147-icedtea"
   OpenJDK Runtime Environment (IcedTea7 2.0) (7~b147-2.0-0ubuntu0.11.10.1)
   OpenJDK 64-Bit Server VM (build 21.0-b17, mixed mode)
3. find / -name java
   /usr/lib/jvm/java-6-openjdk/jre/bin/java
   /usr/lib/jvm/java-6-openjdk/bin/java
   /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
   /usr/lib/jvm/java-7-openjdk-amd64/bin/java
   /usr/lib/ure/share/java
   /usr/share/apport/testsuite/java
   /usr/share/java
   /usr/bin/java
   /var/lib/dpkg/alternatives/java
   /home/aalsaif/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/java
   /home/aalsaif/.rvm/gems/jruby-1.6.5/gems/activerecord-jdbc-adapter-1.2.0/src/java
   /home/aalsaif/.rvm/gems/ruby-1.9.2-p290/gems/json-1.6.1/java
   /home/aalsaif/.rvm/gems/jruby-1.6.5@global/gems/jruby-openssl-0.7.4/test/java
   /etc/bash_completion.d/java
   /etc/ssl/certs/java
   /etc/apparmor.d/abstractions/ubuntu-browsers.d/java
   /etc/alternatives/java
   /etc/java
4. find / -name jdk
   nothing
5. Which linux OS distro - Ubuntu XXX ?? Natty / Marvin / Lucid , etc. & if [64 vs 32 bit OS] & does the jvm also match the OS?
   Ubuntu 11.10 , 64 bit , jvm matches OS

Here is my console output when I run tomighty:

aalsaif@aalsaif-LINUX:~/Downloads$ java -jar tomighty-0.7.1.jar 

(java:7051): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(java:7051): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(java:7051): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(java:7051): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
Nov 29, 2011 10:38:36 PM org.tomighty.log.Log info
INFO: Loading messages for locale en_CA
Nov 29, 2011 10:38:36 PM org.tomighty.log.Log info
INFO: Messages not available for locale en_CA.
Nov 29, 2011 10:38:43 PM org.tomighty.log.Log error
SEVERE: Error while playing sound: org.tomighty.sound.timer.Wind@5731699a
java.lang.IllegalArgumentException: Invalid format
    at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.createStream(PulseAudioDataLine.java:143)
    at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:100)
    at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:289)
    at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:402)
    at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:453)
    at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:72)
    at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:56)
    at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:41)
    at org.tomighty.ui.state.TimerSupport.afterRendering(TimerSupport.java:70)
    at org.tomighty.Tomighty.render(Tomighty.java:94)
    at org.tomighty.Tomighty.access$200(Tomighty.java:45)
    at org.tomighty.Tomighty$SwitchState$1.run(Tomighty.java:104)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:705)
    at java.awt.EventQueue.access$000(EventQueue.java:101)
    at java.awt.EventQueue$3.run(EventQueue.java:666)
    at java.awt.EventQueue$3.run(EventQueue.java:664)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:675)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by ccidral** [comment]
@aalsaif thanks for reporting.  Please could you try running Tomighty on Oracle's Java 7 JRE.  This problem is apparently solved on this JVM, at least on Ubuntu 11.10.

**Comment by aalsaif** [comment]
I just tested it with Oracle Java 7 JDK and the sound is working but I still get this weird Gtk warning .

Oracle Java is no longer supported on Ubuntu as of 11.10. Is there a way to have it working on OpenJDK? 

Cosole output:
aalsaif@aalsaif-LINUX:~/Java/jdk1.7.0_01/bin$ ./java -version
java version "1.7.0_01"
Java(TM) SE Runtime Environment (build 1.7.0_01-b08)
Java HotSpot(TM) 64-Bit Server VM (build 21.1-b02, mixed mode)
aalsaif@aalsaif-LINUX:~/Java/jdk1.7.0_01/bin$ ./java -jar ~/Downloads/tomighty-0.7.1.jar 

(java:16146): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(java:16146): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(java:16146): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(java:16146): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
Nov 30, 2011 8:31:45 PM org.tomighty.log.Log info
INFO: Loading messages for locale en_CA
Nov 30, 2011 8:31:45 PM org.tomighty.log.Log info
INFO: Messages not available for locale en_CA.

**Comment by jarrpa** [comment]
Confirmed issue on Ubuntu 11.10 as well. Also confirmed installing Oracle Java 7 JDK solved the problem. Followed these instructions: http://www.webupd8.org/2011/09/how-to-install-oracle-java-7-jdk-in.html

I would also like to see this working under OpenJDK, but this will work for now.

**Comment by ccidral** [comment]
Well at least it now works with Oracle Java 7 JRE.  I will try to fix this problem with OpenJDK as soon as I get some spare time, which will not happen anytime soon I'm afraid.

**Comment by gustavobarbozamarques-old** [comment]
thanks, i solved this problem. i update to oracle jdk 7 in my linux.
My game: https://sites.google.com/site/asteroidsrain/
