### ISSUE TITLE
Fails to run under OSX in the UK.

### ISSUE THREAD

**Issue by johnstok** [tomighty/tomighty#41]
OSX: 10.6.8
Locale: en_UK

Java version:

```
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03-384-10M3425)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02-384, mixed mode)
```

Output

```
Keiths-iMac:Downloads keith$ java -jar tomighty-0.6.jar 
Jul 9, 2011 6:49:44 PM org.tomighty.log.Log info
INFO: Loading messages for locale en_US
Jul 9, 2011 6:49:44 PM org.tomighty.log.Log info
INFO: Messages file not found: /messages_en_US.properties
Exception in thread "main" java.lang.IllegalArgumentException: input == null!
    at javax.imageio.ImageIO.read(ImageIO.java:1362)
    at org.tomighty.resources.Resources.image(Resources.java:58)
    at org.tomighty.resources.TrayIcons.tomato(TrayIcons.java:76)
    at org.tomighty.resources.TrayIcons.tomato(TrayIcons.java:41)
    at org.tomighty.ui.Tray.initialize(Tray.java:63)
    at org.tomighty.ioc.Factory.create(Factory.java:45)
    at org.tomighty.ioc.Container.get(Container.java:46)
    at org.tomighty.ioc.Container.get(Container.java:39)
    at org.tomighty.Tomighty.main(Tomighty.java:55)
```

**Comment by ccidral** [comment]
Hey @johnstok thanks for reporting this bug.  It's already fixed thanks to @dobermai: https://github.com/ccidral/tomighty/issues/7

I will release the fix in version 0.7 as soon as possible.

**Comment by ccidral** [comment]
Seems like this bug is still present on Tomighty 0.7 under MacOS X Lion 10.7.  I'm fixing it right now.  Below is an error report from Don (elderpro at gmail dot com).

```
Same launch problem with tomighty-0.7.jar on Mac OS X 10.6.8.

A "could not launch" dialog and no Console error messages.  I don't
know if this helps, but in case it might:

7/11/11 5:10:51 PM      [0x0-0x631631].com.apple.JarLauncher[70580]     Notice
Jul 11, 2011 5:10:50 PM org.tomighty.log.Log info
7/11/11 5:10:51 PM      [0x0-0x631631].com.apple.JarLauncher[70580]     Notice
INFO: Loading messages for locale en_US
7/11/11 5:10:51 PM      [0x0-0x631631].com.apple.JarLauncher[70580]     Notice
Jul 11, 2011 5:10:51 PM org.tomighty.log.Log info
7/11/11 5:10:51 PM      [0x0-0x631631].com.apple.JarLauncher[70580]     Notice
INFO: Messages not available for locale en_US.
7/11/11 5:10:51 PM      [0x0-0x631631].com.apple.JarLauncher[70580]     Notice
Exception in thread "main"
7/11/11 5:10:51 PM      [0x0-0x631631].com.apple.JarLauncher[70580]     Notice
java.lang.IllegalArgumentException: creating TrayIcon with null Image
7/11/11 5:10:51 PM      [0x0-0x631631].com.apple.JarLauncher[70580]     Notice
at java.awt.TrayIcon.<init>(TrayIcon.java:159)
7/11/11 5:10:51 PM      [0x0-0x631631].com.apple.JarLauncher[70580]     Notice
at org.tomighty.ui.TrayManager.initialize(TrayManager.java:63)
7/11/11 5:10:51 PM      [0x0-0x631631].com.apple.JarLauncher[70580]     Notice
at org.tomighty.ioc.Factory.create(Factory.java:45)
7/11/11 5:10:51 PM      [0x0-0x631631].com.apple.JarLauncher[70580]     Notice
at org.tomighty.ioc.Container.create(Container.java:61)
7/11/11 5:10:51 PM      [0x0-0x631631].com.apple.JarLauncher[70580]     Notice
at org.tomighty.ioc.Container.get(Container.java:50)
7/11/11 5:10:51 PM      [0x0-0x631631].com.apple.JarLauncher[70580]     Notice
at org.tomighty.ioc.Container.get(Container.java:43)
7/11/11 5:10:51 PM      [0x0-0x631631].com.apple.JarLauncher[70580]     Notice
at org.tomighty.Tomighty.main(Tomighty.java:58)
```

**Comment by ccidral** [comment]
@johnstok please try the latest version of Tomighty under MacOSX Lion, let me know whether it works or not.  I will close this issue in case it works.

**Comment by ccidral** [comment]
A friend of mine ran Tomighty under Lion and said it runs fine, so I'm closing this.
