### ISSUE TITLE
Doesn't start in Xfce + AWN

### ISSUE THREAD

**Issue by eugene-krivobokov** [tomighty/tomighty#50]
```
java -jar tomighty-0.7.1.jar     [15:13:43]
Oct 5, 2011 3:14:00 PM org.tomighty.log.Log info
INFO: Loading messages for locale en_US
Oct 5, 2011 3:14:00 PM org.tomighty.log.Log info
INFO: Messages not available for locale en_US.
Exception in thread "main" java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
    at java.awt.SystemTray.getSystemTray(SystemTray.java:151)
    at org.tomighty.ui.tray.AwtTray.iconSize(AwtTray.java:28)
    at org.tomighty.resources.TrayIcons.tomato(TrayIcons.java:43)
    at org.tomighty.ui.TrayManager.initialize(TrayManager.java:63)
    at org.tomighty.ioc.Factory.create(Factory.java:45)
    at org.tomighty.ioc.Container.create(Container.java:61)
    at org.tomighty.ioc.Container.get(Container.java:50)
    at org.tomighty.ioc.Container.get(Container.java:43)
    at org.tomighty.Tomighty.main(Tomighty.java:58)
```

```
java -version                    [15:19:03]
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) Server VM (build 20.1-b02, mixed mode)

```

```
 uname -a                         [15:14:00]
Linux ek-laptop 2.6.38-11-generic-pae #50-Ubuntu SMP Mon Sep 12 22:21:04 UTC 2011 i686 i686 i386 GNU/Linux
```

XFCE 4.8.0

```
lsb_release -a                   [15:14:53]
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 11.04
Release:    11.04
Codename:   natty
```

I use Awn 0.4.1 with Indicator applet.

**Comment by LukenShiro** [comment]
Unfortunately it doesn't work with LXDE, too. It seems to definitely need a system tray.

**Comment by jvoisin** [comment]
```
jvoisin@kaa 1:57 ~/dev java -jar ./tomighty-0.7.1.ja
Nov 07, 2013 1:57:20 AM org.tomighty.log.Log info
INFO: Loading messages for locale en_US
Nov 07, 2013 1:57:20 AM org.tomighty.log.Log info
INFO: Messages not available for locale en_US.
Nov 07, 2013 1:57:25 AM org.tomighty.log.Log error
SEVERE: Error while playing sound: org.tomighty.sound.timer.Wind@2b5476cc
java.lang.IllegalArgumentException: Invalid format
    at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.createStream(PulseAudioDataLine.java:142)
    at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:99)
    at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:283)
    at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:402)
    at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:453)
    at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:72)
    at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:56)
    at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:41)
    at org.tomighty.ui.state.TimerSupport.afterRendering(TimerSupport.java:70)
    at org.tomighty.Tomighty.render(Tomighty.java:94)
    at org.tomighty.Tomighty.access$200(Tomighty.java:45)
    at org.tomighty.Tomighty$SwitchState$1.run(Tomighty.java:104)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

But it works.

```
jvoisin@kaa 2:02 ~ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 13.10
Release:    13.10
Codename:   saucy
```

```
jvoisin@kaa 2:03 ~ xfce4-about -V
xfce4-about 4.10.0 (Xfce 4.10)

Copyright (c) 2008-2011
    The Xfce development team. All rights reserved.

Please report bugs to <http://bugzilla.xfce.org/>.
Translators list from 2012-04-22 00:21:09.
```

**Comment by androclus** [comment]
i have been using tomighty for quite a while now, and loving it.

but unfortunately, i am now dead in the water, too. just recently, i too started getting this error, too:

$ /usr/bin/java -jar tomighty-0.7.1.jar
Jul 08, 2015 7:04:40 AM org.tomighty.log.Log info
INFO: Loading messages for locale en_US
Jul 08, 2015 7:04:40 AM org.tomighty.log.Log info
INFO: Messages not available for locale en_US.
Exception in thread "main" java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
        at java.awt.SystemTray.getSystemTray(SystemTray.java:186)
        at org.tomighty.ui.tray.AwtTray.iconSize(AwtTray.java:28)
        at org.tomighty.resources.TrayIcons.tomato(TrayIcons.java:43)
        at org.tomighty.ui.TrayManager.initialize(TrayManager.java:63)
        at org.tomighty.ioc.Factory.create(Factory.java:45)
        at org.tomighty.ioc.Container.create(Container.java:61)
        at org.tomighty.ioc.Container.get(Container.java:50)
        at org.tomighty.ioc.Container.get(Container.java:43)
        at org.tomighty.Tomighty.main(Tomighty.java:58)

it does not appear to be sound-related.

i am on linux/ubuntu 15.04, running KDE 5, and
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

let me know if there is any other information i can provide. thx -js

**Comment by satoshi** [comment]
See if adding "Notification Area" to your panel helps with this.  It worked for me when I added it.
