### ISSUE TITLE
Cannot start tomighty in Ubuntu 11.10 with Unity 2D

### ISSUE THREAD

**Issue by haocheng** [tomighty/tomighty#52]
Hi, 

I just upgraded to Ubuntu 11.10 yesterday and found that tomight 0.7.1 won't work with Unity 2D. 
However, it does work with Unity.

Here's the error messages I got:

```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.awt.AWTException: TrayIcon couldn't be displayed.
    at org.tomighty.ui.TrayManager.run(TrayManager.java:75)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:641)
    at java.awt.EventQueue.access$000(EventQueue.java:84)
    at java.awt.EventQueue$1.run(EventQueue.java:602)
    at java.awt.EventQueue$1.run(EventQueue.java:600)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:611)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.awt.AWTException: TrayIcon couldn't be displayed.
    at sun.awt.X11.XTrayIconPeer.<init>(XTrayIconPeer.java:268)
    at sun.awt.X11.XToolkit.createTrayIcon(XToolkit.java:884)
    at java.awt.TrayIcon.addNotify(TrayIcon.java:690)
    at java.awt.SystemTray.add(SystemTray.java:237)
    at org.tomighty.ui.TrayManager.run(TrayManager.java:73)
    ... 14 more
```

Thank you!

**Comment by robertrv** [comment]
+1 on this issue !

**Comment by ccidral** [comment]
Does it still fail on Unity 2D?  I have switched away from Ubuntu 11 to Linux Mint (Gnome 3) so I will have to setup a virtual machine with Ubuntu 11 in order to check it out.

**Comment by haocheng** [comment]
Hi, 

I am not using Unity and Ubuntu 11.10 since it's not stable enough (changed back to Ubuntu 11.04 and GNOME 2 now). I tried to install 11.04 in VirtualBox and run tomighty 0.7.1 with OpenJDK 1.6.0_23 and still the same error.

Thank you :)

**Comment by ccidral** [comment]
The tray icon does not work on Gnome 3 either.

**Comment by haocheng** [comment]
I tried tomighty on Ubuntu 11.10 Unity and it's not working, either... (I tried both OpenJDK 6 and OpenJDK 7)
Same error message.

Thank you!

**Comment by nuk** [comment]
Same here.
The tray icon seems to be a general problem on Unity since other apps also show errors with that.

**Comment by jarod** [comment]
same issue

**Comment by marthjod** [comment]
Same error here (Unity 2D as well as GNOME Classic on Ubuntu 12.04.1). Would be great not having to use Unity "3D" when I want to use tomighty. Works fine on standard Debian Squeeze's GNOME, though.

**Comment by floe** [comment]
Had the same issue with Unity 2D on Ubuntu 12.04.2.
A workaround is described here: https://groups.google.com/d/msg/tomighty/MOvHKgdDTH8/40KIbOeUnKwJ
Note: I had to set the whitelist to ["all"] to make this work.
