### ISSUE TITLE
Exception under MacOS

### ISSUE THREAD

**Issue by ccidral** [tomighty/tomighty#7]
This is what happens when running Tomighty under MacOS:

```
    Exception in thread "main" java.lang.IllegalArgumentException: input == null!
            at javax.imageio.ImageIO.read(ImageIO.java:1362)
            at org.tomighty.resources.Resources.image(Resources.java:58)
            at org.tomighty.resources.TrayIcons.tomato(TrayIcons.java:76)
            at org.tomighty.resources.TrayIcons.tomato(TrayIcons.java:41)
            at org.tomighty.ui.Tray.initialize(Tray.java:63)
            at org.tomighty.ioc.Factory.create(Factory.java:45)
            at org.tomighty.ioc.Container.get(Container.java:46)
            at org.tomighty.ioc.Container.get(Container.java:39)
            at org.tomighty.Tomighty.main(Tomighty.java:55)
```

Reported by @dobermai

**Comment by dobermai** [comment]
Fixed in commit 87cdecaff1923161e059c114bf347366b1e8aab3 .
