### ISSUE TITLE
No sound on Ubuntu 13.04

### ISSUE THREAD

**Issue by guillaumemarcade** [tomighty/tomighty#96]
I get this error when tomighty is trying to play a sound.

```
févr. 04, 2014 4:38:34 PM org.tomighty.log.Log error
Grave: Error while playing sound: org.tomighty.sound.timer.Ding@7980a595
java.lang.IllegalArgumentException: Invalid format
    at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.createStream(PulseAudioDataLine.java:142)
    at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:99)
    at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:283)
    at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:402)
    at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:453)
    at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:72)
    at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:56)
    at org.tomighty.sound.SoundPlayer.play(SoundPlayer.java:41)
    at org.tomighty.ui.state.TimerSupport$EndTimer.receive(TimerSupport.java:116)
    at org.tomighty.ui.state.TimerSupport$EndTimer.receive(TimerSupport.java:113)
    at org.tomighty.bus.Bus.publish(Bus.java:66)
    at org.tomighty.time.CountdownTimer$Updater.run(CountdownTimer.java:58)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
```

Stackoverflow topics on this error : 
- http://stackoverflow.com/questions/18942424/error-playing-audio-file-from-java-via-pulseaudio-on-ubuntu
- http://stackoverflow.com/questions/16001379/play-wav-file-in-jar-java-netbeans

**Comment by ccidral** [comment]
Hi @guillaumemarcade, this issue is a duplicate of #17. What version of Java are you running?

**Comment by guillaumemarcade** [comment]
OK my bad I haven't seen this issue.

I had open-jdk and installed oracle's one. Now it works fine.

Thanks

**Comment by ccidral** [comment]
No problem :)
